[2024-03-27 18:45:15,129: INFO: main: hi]
[2024-03-27 18:48:46,531: INFO: main: hi]
[2024-03-27 19:25:49,117: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-27 19:25:49,117: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-27 19:25:49,117: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-27 19:25:49,117: INFO: common: created directory at: artifacts]
[2024-03-27 19:25:49,117: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-27 19:25:49,117: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-27 19:25:59,203: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-27 19:25:59,963: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-27 19:47:39,072: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-27 19:56:59,124: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-27 19:56:59,136: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-27 19:56:59,141: INFO: common: created directory at: artifacts]
[2024-03-27 19:56:59,144: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-27 19:57:59,126: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-27 19:57:59,321: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-27 19:58:44,872: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-27 19:58:44,875: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-27 19:58:44,877: INFO: common: created directory at: artifacts]
[2024-03-27 19:58:44,879: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-27 19:58:45,202: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-27 19:58:45,285: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-27 19:59:00,213: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-27 19:59:00,215: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-27 19:59:00,218: INFO: common: created directory at: artifacts]
[2024-03-27 19:59:00,219: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-27 19:59:00,484: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-27 19:59:00,599: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-27 19:59:12,029: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-27 19:59:12,031: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-27 19:59:12,033: INFO: common: created directory at: artifacts]
[2024-03-27 19:59:12,034: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-27 19:59:12,326: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-27 19:59:12,411: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-27 20:37:25,433: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-27 20:37:25,978: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-27 20:37:25,978: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-27 20:37:25,978: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-27 20:37:25,978: INFO: common: created directory at: artifacts]
[2024-03-27 20:37:25,978: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-27 20:37:25,978: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-27 20:37:39,906: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-27 20:37:40,716: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-27 20:37:40,716: INFO: main: *******************]
[2024-03-27 20:37:40,716: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-27 20:37:40,719: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-27 20:37:40,719: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-27 20:37:40,719: INFO: common: created directory at: artifacts]
[2024-03-27 20:37:40,719: ERROR: main: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config']
Traceback (most recent call last):
  File "D:\kidney disease project tumor\ct-scan-Kidney\main.py", line 24, in <module>
    prepare_base_model.main()
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config'
[2024-03-27 20:41:48,904: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-27 20:41:49,478: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-27 20:41:49,478: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-27 20:41:49,478: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-27 20:41:49,478: INFO: common: created directory at: artifacts]
[2024-03-27 20:41:49,478: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-27 20:41:49,478: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-27 20:42:01,791: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-27 20:42:02,472: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-27 20:42:02,472: INFO: main: *******************]
[2024-03-27 20:42:02,472: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-27 20:42:02,472: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-27 20:42:02,472: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-27 20:42:02,472: INFO: common: created directory at: artifacts]
[2024-03-27 20:42:02,472: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-27 20:42:02,980: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-27 20:42:03,217: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-27 20:42:03,336: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 01:12:54,671: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 01:13:15,424: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 01:13:15,424: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 01:13:15,440: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 01:13:15,440: INFO: common: created directory at: artifacts]
[2024-03-28 01:13:15,440: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 01:13:15,440: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 01:13:26,222: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 01:13:27,082: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 01:13:27,082: INFO: main: *******************]
[2024-03-28 01:13:27,082: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 01:13:27,097: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 01:13:27,102: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 01:13:27,110: INFO: common: created directory at: artifacts]
[2024-03-28 01:13:27,117: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 01:13:27,743: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 01:13:28,157: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 01:13:29,993: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 01:15:09,343: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 01:15:09,347: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 01:15:09,348: INFO: common: created directory at: artifacts]
[2024-03-28 01:15:09,351: INFO: common: created directory at: artifacts\training]
[2024-03-28 01:15:09,643: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 01:20:12,246: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 01:20:12,248: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 01:20:12,249: INFO: common: created directory at: artifacts]
[2024-03-28 01:20:12,251: INFO: common: created directory at: artifacts\training]
[2024-03-28 01:20:12,464: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 01:32:42,839: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 01:32:42,841: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 01:32:42,843: INFO: common: created directory at: artifacts]
[2024-03-28 01:32:42,844: INFO: common: created directory at: artifacts\training]
[2024-03-28 01:32:43,062: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 01:33:45,414: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 01:33:45,417: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 01:33:45,418: INFO: common: created directory at: artifacts]
[2024-03-28 01:33:45,419: INFO: common: created directory at: artifacts\training]
[2024-03-28 01:33:45,597: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 01:34:01,834: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 01:34:01,837: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 01:34:01,838: INFO: common: created directory at: artifacts]
[2024-03-28 01:34:01,840: INFO: common: created directory at: artifacts\training]
[2024-03-28 01:34:02,015: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 01:37:26,483: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 01:57:46,827: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 01:57:47,405: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 01:57:47,405: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 01:57:47,405: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 01:57:47,416: INFO: common: created directory at: artifacts]
[2024-03-28 01:57:47,417: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 01:57:47,417: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 01:57:55,816: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 01:57:56,451: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 01:57:56,451: INFO: main: *******************]
[2024-03-28 01:57:56,451: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 01:57:56,451: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 01:57:56,451: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 01:57:56,451: INFO: common: created directory at: artifacts]
[2024-03-28 01:57:56,451: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 01:57:56,942: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 01:57:57,162: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 01:57:57,316: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 01:57:57,316: INFO: main: *******************]
[2024-03-28 01:57:57,316: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-28 01:57:57,316: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 01:57:57,316: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 01:57:57,316: INFO: common: created directory at: artifacts]
[2024-03-28 01:57:57,316: INFO: common: created directory at: artifacts\training]
[2024-03-28 01:57:57,464: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 01:57:58,251: ERROR: main: Unknown variable: <KerasVariable shape=(3, 3, 3, 64), dtype=float32, path=block1_conv1/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "D:\kidney disease project tumor\ct-scan-Kidney\main.py", line 38, in <module>
    model_trainer.main()
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "D:\python\Lib\site-packages\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "D:\python\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\python\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 215, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(3, 3, 3, 64), dtype=float32, path=block1_conv1/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-03-28 02:00:24,075: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 02:00:24,480: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 02:00:24,480: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 02:00:24,495: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 02:00:24,496: INFO: common: created directory at: artifacts]
[2024-03-28 02:00:24,497: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 02:00:24,497: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 02:00:32,352: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 02:00:32,997: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 02:00:32,997: INFO: main: *******************]
[2024-03-28 02:00:32,997: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 02:00:32,997: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 02:00:33,013: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 02:00:33,014: INFO: common: created directory at: artifacts]
[2024-03-28 02:00:33,015: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 02:00:33,419: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 02:00:33,561: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 02:00:33,746: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 02:00:33,746: INFO: main: *******************]
[2024-03-28 02:00:33,746: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-28 02:00:33,746: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 02:00:33,746: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 02:00:33,746: INFO: common: created directory at: artifacts]
[2024-03-28 02:00:33,746: INFO: common: created directory at: artifacts\training]
[2024-03-28 02:00:33,889: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 02:04:11,719: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 02:04:11,945: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-28 02:48:34,751: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 02:48:35,369: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 02:48:35,370: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 02:48:35,371: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 02:48:35,371: INFO: common: created directory at: artifacts]
[2024-03-28 02:48:35,372: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 02:48:35,372: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 02:48:43,717: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 02:48:44,468: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 02:48:44,468: INFO: main: *******************]
[2024-03-28 02:48:44,468: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 02:48:44,468: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 02:48:44,484: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 02:48:44,484: INFO: common: created directory at: artifacts]
[2024-03-28 02:48:44,484: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 02:48:45,048: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 02:48:45,315: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 02:48:45,460: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 02:48:45,460: INFO: main: *******************]
[2024-03-28 02:48:45,460: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-28 02:48:45,460: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 02:48:45,460: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 02:48:45,460: INFO: common: created directory at: artifacts]
[2024-03-28 02:48:45,460: INFO: common: created directory at: artifacts\training]
[2024-03-28 02:48:45,630: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 02:51:02,655: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 02:51:02,655: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 02:51:02,655: INFO: common: created directory at: artifacts]
[2024-03-28 02:52:37,900: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 02:52:38,047: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-28 03:14:48,122: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 03:14:49,827: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 03:14:49,827: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 03:14:49,827: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 03:14:49,827: INFO: common: created directory at: artifacts]
[2024-03-28 03:14:49,827: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 03:14:49,843: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 03:14:58,704: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 03:14:59,329: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 03:14:59,329: INFO: main: *******************]
[2024-03-28 03:14:59,329: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 03:14:59,329: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 03:14:59,329: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 03:14:59,329: INFO: common: created directory at: artifacts]
[2024-03-28 03:14:59,329: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 03:14:59,846: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 03:15:00,142: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 03:15:00,329: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 03:15:00,329: INFO: main: *******************]
[2024-03-28 03:15:00,329: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-28 03:15:00,329: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 03:15:00,329: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 03:15:00,329: INFO: common: created directory at: artifacts]
[2024-03-28 03:15:00,329: INFO: common: created directory at: artifacts\training]
[2024-03-28 03:15:00,496: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 03:18:22,277: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 03:18:22,454: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-28 03:18:22,454: INFO: main: *******************]
[2024-03-28 03:18:22,454: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-28 03:18:22,454: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 03:18:22,454: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 03:18:22,469: INFO: common: created directory at: artifacts]
[2024-03-28 03:18:22,718: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 03:18:40,761: INFO: common: json file saved at: scores.json]
[2024-03-28 03:18:40,761: INFO: common: json file saved at: scores.json]
[2024-03-28 03:18:40,761: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-28 03:26:18,717: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 03:26:20,326: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 03:26:20,326: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 03:26:20,326: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 03:26:20,326: INFO: common: created directory at: artifacts]
[2024-03-28 03:26:20,326: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 03:26:20,326: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 03:26:28,704: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 03:26:29,346: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 03:26:29,346: INFO: main: *******************]
[2024-03-28 03:26:29,346: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 03:26:29,346: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 03:26:29,346: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 03:26:29,346: INFO: common: created directory at: artifacts]
[2024-03-28 03:26:29,346: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 03:26:29,804: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 03:26:29,992: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 03:26:30,136: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 03:26:30,136: INFO: main: *******************]
[2024-03-28 03:26:30,136: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-28 03:26:30,136: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 03:26:30,136: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 03:26:30,136: INFO: common: created directory at: artifacts]
[2024-03-28 03:26:30,136: INFO: common: created directory at: artifacts\training]
[2024-03-28 03:26:30,318: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 03:30:19,456: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 03:30:19,616: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-28 03:30:19,617: INFO: main: *******************]
[2024-03-28 03:30:19,618: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-28 03:30:19,626: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 03:30:19,637: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 03:30:19,637: INFO: common: created directory at: artifacts]
[2024-03-28 03:30:19,882: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 03:30:37,267: INFO: common: json file saved at: scores.json]
[2024-03-28 03:30:37,268: INFO: common: json file saved at: scores.json]
[2024-03-28 03:30:37,268: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-28 03:48:16,126: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 03:48:17,850: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 03:48:17,850: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 03:48:17,850: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 03:48:17,850: INFO: common: created directory at: artifacts]
[2024-03-28 03:48:17,850: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 03:48:17,850: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 03:48:25,781: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 03:48:26,336: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 03:48:26,336: INFO: main: *******************]
[2024-03-28 03:48:26,336: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 03:48:26,336: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 03:48:26,336: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 03:48:26,336: INFO: common: created directory at: artifacts]
[2024-03-28 03:48:26,336: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 03:48:26,727: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 03:48:26,849: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 03:48:26,910: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 03:48:26,910: INFO: main: *******************]
[2024-03-28 03:48:26,910: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-28 03:48:26,925: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 03:48:26,927: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 03:48:26,927: INFO: common: created directory at: artifacts]
[2024-03-28 03:48:26,927: INFO: common: created directory at: artifacts\training]
[2024-03-28 03:48:27,075: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 03:51:54,444: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 03:51:54,511: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-28 03:51:54,512: INFO: main: *******************]
[2024-03-28 03:51:54,512: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-28 03:51:54,513: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 03:51:54,514: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 03:51:54,515: INFO: common: created directory at: artifacts]
[2024-03-28 03:51:54,674: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 03:52:14,299: INFO: common: json file saved at: scores.json]
[2024-03-28 03:52:14,299: INFO: common: json file saved at: scores.json]
[2024-03-28 03:52:14,299: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-28 04:01:13,440: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 04:01:15,205: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 04:01:15,206: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 04:01:15,208: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 04:01:15,209: INFO: common: created directory at: artifacts]
[2024-03-28 04:01:15,209: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 04:01:15,210: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 04:01:23,833: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 04:01:24,511: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 04:01:24,511: INFO: main: *******************]
[2024-03-28 04:01:24,511: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 04:01:24,513: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 04:01:24,513: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 04:01:24,513: INFO: common: created directory at: artifacts]
[2024-03-28 04:01:24,513: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 04:01:24,971: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 04:01:25,216: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 04:01:25,318: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 04:01:25,318: INFO: main: *******************]
[2024-03-28 04:01:25,318: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-28 04:01:25,318: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 04:01:25,318: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 04:01:25,318: INFO: common: created directory at: artifacts]
[2024-03-28 04:01:25,326: INFO: common: created directory at: artifacts\training]
[2024-03-28 04:01:25,488: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 04:05:29,466: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 04:05:29,634: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-28 04:05:29,635: INFO: main: *******************]
[2024-03-28 04:05:29,635: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-28 04:05:29,645: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 04:05:29,648: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 04:05:29,669: INFO: common: created directory at: artifacts]
[2024-03-28 04:05:29,915: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 04:05:53,584: INFO: common: json file saved at: scores.json]
[2024-03-28 04:05:53,587: INFO: common: json file saved at: scores.json]
[2024-03-28 04:06:11,716: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-28 04:43:42,240: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 04:43:43,673: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 04:43:43,673: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 04:43:43,673: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 04:43:43,673: INFO: common: created directory at: artifacts]
[2024-03-28 04:43:43,673: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 04:43:43,673: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 04:43:51,807: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 04:43:52,623: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 04:43:52,623: INFO: main: *******************]
[2024-03-28 04:43:52,623: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 04:43:52,627: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 04:43:52,630: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 04:43:52,630: INFO: common: created directory at: artifacts]
[2024-03-28 04:43:52,630: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 04:43:53,474: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 04:43:53,697: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 04:43:53,877: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 04:43:53,879: INFO: main: *******************]
[2024-03-28 04:43:53,879: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-28 04:43:53,881: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 04:43:53,885: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 04:43:53,886: INFO: common: created directory at: artifacts]
[2024-03-28 04:43:53,888: INFO: common: created directory at: artifacts\training]
[2024-03-28 04:43:54,157: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 04:47:50,345: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 04:47:50,455: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-28 04:47:50,461: INFO: main: *******************]
[2024-03-28 04:47:50,462: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-28 04:47:50,462: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 04:47:50,462: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 04:47:50,472: INFO: common: created directory at: artifacts]
[2024-03-28 04:47:50,696: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 04:48:09,779: INFO: common: json file saved at: scores.json]
[2024-03-28 04:48:09,780: INFO: common: json file saved at: scores.json]
[2024-03-28 04:48:25,612: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-28 17:14:41,920: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 17:14:45,583: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 17:14:45,583: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 17:14:45,583: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 17:14:45,583: INFO: common: created directory at: artifacts]
[2024-03-28 17:14:45,583: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 17:14:45,583: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 17:14:54,842: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 17:14:55,431: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 17:14:55,431: INFO: main: *******************]
[2024-03-28 17:14:55,431: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 17:14:55,431: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 17:14:55,431: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 17:14:55,431: INFO: common: created directory at: artifacts]
[2024-03-28 17:14:55,431: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 17:14:55,877: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 17:14:55,996: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 17:14:56,186: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 17:14:56,186: INFO: main: *******************]
[2024-03-28 17:14:56,186: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-28 17:14:56,186: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 17:14:56,186: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 17:14:56,186: INFO: common: created directory at: artifacts]
[2024-03-28 17:14:56,186: INFO: common: created directory at: artifacts\training]
[2024-03-28 17:14:56,455: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 17:18:54,102: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 17:18:54,232: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-28 17:18:54,232: INFO: main: *******************]
[2024-03-28 17:18:54,232: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-28 17:18:54,250: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 17:18:54,253: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 17:18:54,255: INFO: common: created directory at: artifacts]
[2024-03-28 17:18:54,443: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 17:19:10,171: INFO: common: json file saved at: scores.json]
[2024-03-28 17:19:10,171: INFO: common: json file saved at: scores.json]
[2024-03-28 17:19:36,588: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-28 17:33:48,832: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 17:33:51,096: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 17:33:51,098: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 17:33:51,099: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 17:33:51,100: INFO: common: created directory at: artifacts]
[2024-03-28 17:33:51,100: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 17:33:51,102: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 17:34:00,121: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 17:34:00,705: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 17:34:00,705: INFO: main: *******************]
[2024-03-28 17:34:00,705: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 17:34:00,705: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 17:34:00,721: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 17:34:00,721: INFO: common: created directory at: artifacts]
[2024-03-28 17:34:00,721: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 17:34:01,215: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 17:34:01,318: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 17:34:01,503: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 17:34:01,503: INFO: main: *******************]
[2024-03-28 17:34:01,503: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-28 17:34:01,519: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 17:34:01,519: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 17:34:01,519: INFO: common: created directory at: artifacts]
[2024-03-28 17:34:01,519: INFO: common: created directory at: artifacts\training]
[2024-03-28 17:34:01,643: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 17:37:39,883: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 17:37:40,017: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-28 17:37:40,018: INFO: main: *******************]
[2024-03-28 17:37:40,018: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-28 17:37:40,027: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 17:37:40,030: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 17:37:40,034: INFO: common: created directory at: artifacts]
[2024-03-28 17:37:40,230: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 17:37:57,806: INFO: common: json file saved at: scores.json]
[2024-03-28 17:37:57,806: INFO: common: json file saved at: scores.json]
[2024-03-28 17:38:12,374: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-28 18:06:40,972: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 18:06:42,581: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 18:06:42,581: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:06:42,581: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:06:42,581: INFO: common: created directory at: artifacts]
[2024-03-28 18:06:42,581: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 18:06:42,581: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 18:06:53,758: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 18:06:54,366: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 18:06:54,366: INFO: main: *******************]
[2024-03-28 18:06:54,366: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 18:06:54,366: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:06:54,366: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:06:54,366: INFO: common: created directory at: artifacts]
[2024-03-28 18:06:54,366: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 18:06:54,855: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:06:55,104: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:06:55,240: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 18:06:55,240: INFO: main: *******************]
[2024-03-28 18:06:55,240: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-28 18:06:55,240: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:06:55,240: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:06:55,240: INFO: common: created directory at: artifacts]
[2024-03-28 18:06:55,240: INFO: common: created directory at: artifacts\training]
[2024-03-28 18:06:55,379: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 18:10:04,517: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:10:04,695: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-28 18:10:04,695: INFO: main: *******************]
[2024-03-28 18:10:04,695: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-28 18:10:04,718: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:10:04,719: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:10:04,724: INFO: common: created directory at: artifacts]
[2024-03-28 18:10:04,961: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 18:10:20,610: INFO: common: json file saved at: scores.json]
[2024-03-28 18:10:20,610: INFO: common: json file saved at: scores.json]
[2024-03-28 18:10:20,610: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-28 18:18:39,145: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 18:18:40,787: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 18:18:40,787: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:18:40,787: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:18:40,787: INFO: common: created directory at: artifacts]
[2024-03-28 18:18:40,787: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 18:18:40,787: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 18:18:54,250: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 18:18:54,821: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 18:18:54,821: INFO: main: *******************]
[2024-03-28 18:18:54,821: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 18:18:54,821: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:18:54,821: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:18:54,821: INFO: common: created directory at: artifacts]
[2024-03-28 18:18:54,821: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 18:18:55,229: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:18:55,515: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:18:55,631: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 18:18:55,631: INFO: main: *******************]
[2024-03-28 18:18:55,631: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-28 18:18:55,631: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:18:55,631: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:18:55,631: INFO: common: created directory at: artifacts]
[2024-03-28 18:18:55,631: INFO: common: created directory at: artifacts\training]
[2024-03-28 18:18:55,793: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 18:22:02,763: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:22:02,901: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-28 18:22:02,901: INFO: main: *******************]
[2024-03-28 18:22:02,901: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-28 18:22:02,922: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:22:02,927: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:22:02,931: INFO: common: created directory at: artifacts]
[2024-03-28 18:22:03,149: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 18:22:18,699: INFO: common: json file saved at: scores.json]
[2024-03-28 18:22:18,699: INFO: common: json file saved at: scores.json]
[2024-03-28 18:22:33,866: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-28 18:30:04,808: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 18:30:06,185: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 18:30:06,185: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:30:06,185: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:30:06,185: INFO: common: created directory at: artifacts]
[2024-03-28 18:30:06,185: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 18:30:06,185: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 18:30:40,132: ERROR: main: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\gdown\download.py", line 253, in download
    url = get_url_from_gdrive_confirmation(res.text)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\gdown\download.py", line 54, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\kidney disease project tumor\ct-scan-Kidney\main.py", line 15, in <module>
    data_ingestion.main()
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "D:\python\Lib\site-packages\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "D:\python\Lib\site-packages\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "D:\python\Lib\site-packages\gdown\download.py", line 264, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.
[2024-03-28 18:32:58,333: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 18:32:59,692: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 18:32:59,692: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:32:59,692: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:32:59,692: INFO: common: created directory at: artifacts]
[2024-03-28 18:32:59,692: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 18:32:59,692: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 18:33:12,651: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 18:33:13,301: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 18:33:13,302: INFO: main: *******************]
[2024-03-28 18:33:13,302: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 18:33:13,304: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:33:13,305: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:33:13,305: INFO: common: created directory at: artifacts]
[2024-03-28 18:33:13,306: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 18:33:13,721: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:33:13,943: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:33:14,099: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 18:33:14,099: INFO: main: *******************]
[2024-03-28 18:33:14,100: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-28 18:33:14,101: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:33:14,102: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:33:14,103: INFO: common: created directory at: artifacts]
[2024-03-28 18:33:14,103: INFO: common: created directory at: artifacts\training]
[2024-03-28 18:33:14,261: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 18:36:31,433: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:36:31,611: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-28 18:36:31,611: INFO: main: *******************]
[2024-03-28 18:36:31,611: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-28 18:36:31,633: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:36:31,635: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:36:31,638: INFO: common: created directory at: artifacts]
[2024-03-28 18:36:31,934: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 18:36:49,817: INFO: common: json file saved at: scores.json]
[2024-03-28 18:36:49,817: INFO: common: json file saved at: scores.json]
[2024-03-28 18:37:05,718: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-28 18:41:15,513: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 18:41:16,875: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 18:41:16,875: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:41:16,875: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:41:16,875: INFO: common: created directory at: artifacts]
[2024-03-28 18:41:16,875: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 18:41:16,875: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 18:41:25,870: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 18:41:26,499: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 18:41:26,499: INFO: main: *******************]
[2024-03-28 18:41:26,499: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 18:41:26,499: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:41:26,504: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:41:26,504: INFO: common: created directory at: artifacts]
[2024-03-28 18:41:26,504: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 18:41:26,884: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:41:26,985: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:41:27,100: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 18:41:27,100: INFO: main: *******************]
[2024-03-28 18:41:27,100: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-28 18:41:27,100: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:41:27,100: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:41:27,100: INFO: common: created directory at: artifacts]
[2024-03-28 18:41:27,100: INFO: common: created directory at: artifacts\training]
[2024-03-28 18:41:27,283: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 18:44:34,026: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:44:34,129: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-28 18:44:34,130: INFO: main: *******************]
[2024-03-28 18:44:34,130: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-28 18:44:34,134: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:44:34,136: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:44:34,138: INFO: common: created directory at: artifacts]
[2024-03-28 18:44:34,289: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 18:44:51,098: INFO: common: json file saved at: scores.json]
[2024-03-28 18:44:51,114: INFO: common: json file saved at: scores.json]
[2024-03-28 18:45:05,195: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-28 18:47:26,644: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 18:47:27,973: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 18:47:27,973: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:47:27,973: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:47:27,973: INFO: common: created directory at: artifacts]
[2024-03-28 18:47:27,973: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 18:47:27,973: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 18:47:37,247: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 18:47:37,834: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 18:47:37,834: INFO: main: *******************]
[2024-03-28 18:47:37,849: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 18:47:37,849: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:47:37,849: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:47:37,849: INFO: common: created directory at: artifacts]
[2024-03-28 18:47:37,849: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 18:47:38,243: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:47:38,374: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:47:38,451: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 18:47:38,451: INFO: main: *******************]
[2024-03-28 18:47:38,451: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-28 18:47:38,453: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:47:38,454: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:47:38,455: INFO: common: created directory at: artifacts]
[2024-03-28 18:47:38,455: INFO: common: created directory at: artifacts\training]
[2024-03-28 18:47:38,593: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 18:50:47,257: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:50:47,343: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-28 18:50:47,344: INFO: main: *******************]
[2024-03-28 18:50:47,344: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-28 18:50:47,345: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:50:47,347: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:50:47,348: INFO: common: created directory at: artifacts]
[2024-03-28 18:50:47,512: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 18:51:05,263: INFO: common: json file saved at: scores.json]
[2024-03-28 18:51:05,263: INFO: common: json file saved at: scores.json]
[2024-03-28 18:51:36,075: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-28 18:52:20,443: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 18:52:22,005: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 18:52:22,005: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:52:22,005: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:52:22,005: INFO: common: created directory at: artifacts]
[2024-03-28 18:52:22,005: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 18:52:22,005: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 18:52:30,598: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 18:52:31,185: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 18:52:31,185: INFO: main: *******************]
[2024-03-28 18:52:31,185: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 18:52:31,185: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:52:31,185: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:52:31,185: INFO: common: created directory at: artifacts]
[2024-03-28 18:52:31,185: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 18:52:31,557: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:52:31,681: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:52:31,754: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 18:52:31,754: INFO: main: *******************]
[2024-03-28 18:52:31,754: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-28 18:52:31,756: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:52:31,757: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:52:31,758: INFO: common: created directory at: artifacts]
[2024-03-28 18:52:31,758: INFO: common: created directory at: artifacts\training]
[2024-03-28 18:52:31,906: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 18:55:49,915: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 18:55:49,978: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-28 18:55:49,978: INFO: main: *******************]
[2024-03-28 18:55:49,978: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-28 18:55:49,995: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 18:55:49,997: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 18:55:49,997: INFO: common: created directory at: artifacts]
[2024-03-28 18:55:50,174: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-28 18:56:07,269: INFO: common: json file saved at: scores.json]
[2024-03-28 18:56:07,269: INFO: common: json file saved at: scores.json]
[2024-03-28 18:56:38,434: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-28 23:56:14,177: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-28 23:56:14,181: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 23:56:14,183: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 23:56:14,188: INFO: common: created directory at: artifacts]
[2024-03-28 23:56:14,191: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-28 23:56:14,201: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 23:56:24,723: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-28 23:56:25,988: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-28 23:56:40,872: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 23:56:41,386: INFO: stage_02_prepare_base_model: *******************]
[2024-03-28 23:56:41,387: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-28 23:56:41,389: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 23:56:41,390: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 23:56:41,392: INFO: common: created directory at: artifacts]
[2024-03-28 23:56:41,393: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-28 23:56:41,937: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 23:56:42,210: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-28 23:56:42,311: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-28 23:56:48,907: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-28 23:56:49,235: INFO: stage_03_model_training: *******************]
[2024-03-28 23:56:49,235: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-03-28 23:56:49,237: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-28 23:56:49,238: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-28 23:56:49,238: INFO: common: created directory at: artifacts]
[2024-03-28 23:56:49,239: INFO: common: created directory at: artifacts\training]
[2024-03-28 23:56:49,602: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 00:01:34,060: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-29 00:01:34,291: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-29 00:01:45,325: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 00:01:49,258: INFO: stage_04_model_evaluation: *******************]
[2024-03-29 00:01:49,258: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-29 00:01:49,260: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-29 00:01:49,262: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-29 00:01:49,262: INFO: common: created directory at: artifacts]
[2024-03-29 00:01:49,540: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 00:02:10,039: INFO: common: json file saved at: scores.json]
[2024-03-29 00:02:10,040: INFO: common: json file saved at: scores.json]
[2024-03-29 00:02:43,351: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-29 00:32:44,178: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 00:32:48,571: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.122.191:8080]
[2024-03-29 00:32:48,571: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-29 00:33:02,841: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 00:33:02] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:33:10,356: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:33:10] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:33:54,654: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\kidney disease project tumor\ct-scan-Kidney\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\prediction.py", line 15, in predict
    model =  tf.keras.models.load_model(os.path.join("model", "model.h5"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(filepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-03-29 00:33:54,670: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:33:54] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-29 00:34:49,416: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:34:49] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:34:54,130: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\kidney disease project tumor\ct-scan-Kidney\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\prediction.py", line 15, in predict
    model =  tf.keras.models.load_model(os.path.join("model", "model.h5"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(filepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-03-29 00:34:54,137: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:34:54] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-29 00:36:14,226: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:36:14] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:36:15,682: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\kidney disease project tumor\ct-scan-Kidney\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\prediction.py", line 15, in predict
    model =  tf.keras.models.load_model(os.path.join("model", "model.h5"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(filepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-03-29 00:36:15,690: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:36:15] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-29 00:36:25,521: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:36:25] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:07,885: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 00:38:08,426: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.122.191:8080]
[2024-03-29 00:38:08,426: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-29 00:38:08,518: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:08] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:09,848: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:09] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:10,404: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:10] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:10,581: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:10] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:10,746: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:10] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:10,933: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:10] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:11,090: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:11] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:11,259: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:11] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:11,462: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:11] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:11,640: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:11] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:11,809: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:11] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:11,990: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:11] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:12,168: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:12] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:12,363: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:12] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:12,518: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:12] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:12,675: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:12] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:12,835: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:12] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:13,056: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:13] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:38:14,150: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\kidney disease project tumor\ct-scan-Kidney\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\prediction.py", line 15, in predict
    model =  tf.keras.models.load_model(os.path.join("model", "model.h5"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(filepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-03-29 00:38:14,151: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:38:14] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-29 00:42:55,272: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:42:55] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:43:00,037: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:43:00] "[33mGET /training HTTP/1.1[0m" 404 -]
[2024-03-29 00:43:00,082: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:43:00] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2024-03-29 00:43:14,652: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:43:14] "GET /train HTTP/1.1" 200 -]
[2024-03-29 00:43:58,401: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:43:58] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:44:00,338: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\kidney disease project tumor\ct-scan-Kidney\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\prediction.py", line 15, in predict
    model =  tf.keras.models.load_model(os.path.join("model", "model.h5"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(filepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-03-29 00:44:00,348: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:44:00] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-29 00:45:21,323: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:45:21] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:45:22,489: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\kidney disease project tumor\ct-scan-Kidney\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\prediction.py", line 15, in predict
    model =  tf.keras.models.load_model(os.path.join("model", "model.h5"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(filepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-03-29 00:45:22,505: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:45:22] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-29 00:45:46,560: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:45:46] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:45:58,214: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\kidney disease project tumor\ct-scan-Kidney\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\prediction.py", line 15, in predict
    model =  tf.keras.models.load_model(os.path.join("model", "model.h5"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(filepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-03-29 00:45:58,223: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:45:58] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-29 00:46:43,208: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 00:46:45,259: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.122.191:8080]
[2024-03-29 00:46:45,259: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-29 00:46:50,078: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:46:50] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:46:51,531: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\kidney disease project tumor\ct-scan-Kidney\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\prediction.py", line 15, in predict
    model =  tf.keras.models.load_model(os.path.join("model", "model.h5"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(filepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-03-29 00:46:51,541: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:46:51] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-29 00:51:28,575: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 00:51:29,031: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.122.191:8080]
[2024-03-29 00:51:29,031: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-29 00:51:39,009: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:51:39] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:51:46,283: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2024-03-29 00:51:47,063: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\kidney disease project tumor\ct-scan-Kidney\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\prediction.py", line 24, in predict
    if result[0] == 1:
       ^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[2024-03-29 00:51:47,070: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:51:47] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-29 00:55:06,025: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 00:55:06,640: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.122.191:8080]
[2024-03-29 00:55:06,641: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-29 00:55:15,778: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:55:15] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:55:18,883: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2024-03-29 00:55:19,121: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\kidney disease project tumor\ct-scan-Kidney\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\prediction.py", line 18, in predict
    test_image = tf.keras.preprocessing.image.load_img(imagename, target_size = (224,224))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\utils\image_utils.py", line 236, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\PIL\Image.py", line 3309, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000002CCCBCD1260>
[2024-03-29 00:55:19,121: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:55:19] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-29 00:55:37,313: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:55:37] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:55:41,445: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2024-03-29 00:55:42,219: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\kidney disease project tumor\ct-scan-Kidney\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\prediction.py", line 24, in predict
    if result[0] == 1:
       ^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[2024-03-29 00:55:42,222: INFO: _internal: 172.16.122.191 - - [29/Mar/2024 00:55:42] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-29 00:56:55,533: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 00:56:56,060: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.122.191:8080]
[2024-03-29 00:56:56,061: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-29 00:56:59,328: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 00:56:59] "GET / HTTP/1.1" 200 -]
[2024-03-29 00:57:09,842: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2024-03-29 00:57:10,556: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\kidney disease project tumor\ct-scan-Kidney\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\prediction.py", line 24, in predict
    if result[0] == 1:
       ^^^^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[2024-03-29 00:57:10,605: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 00:57:10] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-29 01:01:17,320: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 01:01:17,777: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.122.191:8080]
[2024-03-29 01:01:17,777: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-29 01:01:23,508: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:01:23] "GET / HTTP/1.1" 200 -]
[2024-03-29 01:01:32,409: WARNING: legacy_h5_format: No training configuration found in the save file, so the model was *not* compiled. Compile it manually.]
[2024-03-29 01:01:33,156: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\kidney disease project tumor\ct-scan-Kidney\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\prediction.py", line 27, in predict
    if result == 1:
       ^^^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[2024-03-29 01:01:33,173: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:01:33] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-29 01:26:06,666: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 01:26:07,081: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.122.191:8080]
[2024-03-29 01:26:07,081: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-29 01:26:12,170: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:26:12] "GET / HTTP/1.1" 200 -]
[2024-03-29 01:26:19,682: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 01:26:20,263: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:26:20] "POST /predict HTTP/1.1" 200 -]
[2024-03-29 01:26:29,863: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 01:26:30,428: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:26:30] "POST /predict HTTP/1.1" 200 -]
[2024-03-29 01:26:45,676: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 01:26:46,273: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:26:46] "POST /predict HTTP/1.1" 200 -]
[2024-03-29 01:27:41,439: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 01:27:41,927: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.122.191:8080]
[2024-03-29 01:27:41,927: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-29 01:41:39,330: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:41:39] "GET / HTTP/1.1" 200 -]
[2024-03-29 01:41:45,540: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 01:41:46,821: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:41:46] "POST /predict HTTP/1.1" 200 -]
[2024-03-29 01:41:54,758: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 01:41:55,340: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:41:55] "POST /predict HTTP/1.1" 200 -]
[2024-03-29 01:42:05,505: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 01:42:05,970: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:42:05] "POST /predict HTTP/1.1" 200 -]
[2024-03-29 01:43:00,562: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 01:43:01,050: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.122.191:8080]
[2024-03-29 01:43:01,050: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-29 01:43:03,805: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:43:03] "GET / HTTP/1.1" 200 -]
[2024-03-29 01:43:07,656: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 01:43:07,769: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\python\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\kidney disease project tumor\ct-scan-Kidney\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\cnnClassifier\pipeline\prediction.py", line 20, in predict
    test_image = tf.keras.preprocessing.image.load_img(imagename, target_size = (224,224))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\keras\src\utils\image_utils.py", line 236, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\PIL\Image.py", line 3309, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000010CD502BC40>
[2024-03-29 01:43:07,775: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:43:07] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-29 01:43:11,597: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:43:11] "GET / HTTP/1.1" 200 -]
[2024-03-29 01:43:15,865: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 01:43:16,462: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:43:16] "POST /predict HTTP/1.1" 200 -]
[2024-03-29 01:43:23,007: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 01:43:23,554: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:43:23] "POST /predict HTTP/1.1" 200 -]
[2024-03-29 01:49:27,631: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 01:49:29,335: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-29 01:49:29,335: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-29 01:49:29,335: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-29 01:49:29,351: INFO: common: created directory at: artifacts]
[2024-03-29 01:49:29,351: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-29 01:49:29,351: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-29 01:49:38,168: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-29 01:49:38,744: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-29 01:49:38,744: INFO: main: *******************]
[2024-03-29 01:49:38,744: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-29 01:49:38,744: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-29 01:49:38,744: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-29 01:49:38,744: INFO: common: created directory at: artifacts]
[2024-03-29 01:49:38,744: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-29 01:49:39,213: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-29 01:49:39,377: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-29 01:49:39,539: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-29 01:49:39,539: INFO: main: *******************]
[2024-03-29 01:49:39,539: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-29 01:49:39,539: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-29 01:49:39,539: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-29 01:49:39,539: INFO: common: created directory at: artifacts]
[2024-03-29 01:49:39,539: INFO: common: created directory at: artifacts\training]
[2024-03-29 01:49:39,698: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 01:52:53,336: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-03-29 01:52:53,500: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-29 01:52:53,516: INFO: main: *******************]
[2024-03-29 01:52:53,516: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-29 01:52:53,531: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-29 01:52:53,535: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-29 01:52:53,537: INFO: common: created directory at: artifacts]
[2024-03-29 01:52:53,794: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 01:53:10,077: INFO: common: json file saved at: scores.json]
[2024-03-29 01:53:10,093: INFO: common: json file saved at: scores.json]
[2024-03-29 01:53:46,324: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-29 01:54:14,548: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 01:54:15,054: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.122.191:8080]
[2024-03-29 01:54:15,054: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-29 01:54:21,932: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:54:21] "GET / HTTP/1.1" 200 -]
[2024-03-29 01:54:44,688: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 01:54:45,336: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:54:45] "POST /predict HTTP/1.1" 200 -]
[2024-03-29 01:54:53,392: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 01:54:53,939: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:54:53] "POST /predict HTTP/1.1" 200 -]
[2024-03-29 01:55:02,709: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 01:55:03,224: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:55:03] "POST /predict HTTP/1.1" 200 -]
[2024-03-29 01:55:09,536: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 01:55:10,117: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:55:10] "POST /predict HTTP/1.1" 200 -]
[2024-03-29 01:55:16,130: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-29 01:55:16,662: WARNING: polymorphic_function: 5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000020F401B7060> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-29 01:55:16,678: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:55:16] "POST /predict HTTP/1.1" 200 -]
[2024-03-29 01:57:51,950: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 01:57:52,376: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.122.191:8080]
[2024-03-29 01:57:52,377: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-29 01:57:54,990: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:57:54] "GET / HTTP/1.1" 200 -]
[2024-03-29 01:58:59,219: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 01:58:59,625: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.122.191:8080]
[2024-03-29 01:58:59,625: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-29 01:59:03,878: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:59:03] "GET / HTTP/1.1" 200 -]
[2024-03-29 01:59:45,367: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:59:45] "GET / HTTP/1.1" 200 -]
[2024-03-29 01:59:57,932: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 01:59:58,357: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.122.191:8080]
[2024-03-29 01:59:58,358: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-29 01:59:58,467: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 01:59:58] "GET / HTTP/1.1" 200 -]
[2024-03-29 02:00:00,497: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 02:00:00] "GET / HTTP/1.1" 200 -]
[2024-03-29 02:00:00,883: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 02:00:00] "GET / HTTP/1.1" 200 -]
[2024-03-29 02:00:01,038: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 02:00:01] "GET / HTTP/1.1" 200 -]
[2024-03-29 02:00:01,227: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 02:00:01] "GET / HTTP/1.1" 200 -]
[2024-03-29 02:00:01,431: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 02:00:01] "GET / HTTP/1.1" 200 -]
[2024-03-29 02:00:50,443: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-03-29 02:00:50,863: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.16.122.191:8080]
[2024-03-29 02:00:50,865: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-29 02:00:53,010: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 02:00:53] "GET / HTTP/1.1" 200 -]
[2024-03-29 02:00:54,273: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 02:00:54] "GET / HTTP/1.1" 200 -]
[2024-03-29 02:00:55,016: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 02:00:55] "GET / HTTP/1.1" 200 -]
[2024-03-29 02:00:55,198: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 02:00:55] "GET / HTTP/1.1" 200 -]
[2024-03-29 02:00:55,397: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 02:00:55] "GET / HTTP/1.1" 200 -]
[2024-03-29 02:00:55,596: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 02:00:55] "GET / HTTP/1.1" 200 -]
[2024-03-29 02:00:55,813: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 02:00:55] "GET / HTTP/1.1" 200 -]
[2024-03-29 02:00:56,076: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 02:00:56] "GET / HTTP/1.1" 200 -]
[2024-03-29 02:00:56,277: INFO: _internal: 127.0.0.1 - - [29/Mar/2024 02:00:56] "GET / HTTP/1.1" 200 -]
